/// Oferta de grado UTN para el selector de registro.
const utnCareers = <String>[
  'Administración de Empresas',
  'Agroindustria',
  'Agropecuaria',
  'Biotecnología',
  'Ciencia de Datos e Inteligencia Artificial',
  'Comunicación',
  'Contabilidad y Auditoría',
  'Criminología y Ciencias Forenses',
  'Derecho',
  'Educación Básica',
  'Educación Inicial',
  'Electricidad',
  'Enfermería',
  'Entrenamiento Deportivo',
  'Gastronomía',
  'Ingeniería Ambiental',
  'Ingeniería Automotriz',
  'Ingeniería en Energías Renovables',
  'Ingeniería Industrial',
  'Mecatrónica',
  'Medicina',
  'Medicina Veterinaria',
  'Mercadotecnia',
  'Negocios Digitales',
  'Nutrición y Dietética',
  'Pedagogía de la Actividad Física y Deporte',
  'Pedagogía de las Artes y las Humanidades',
  'Pedagogía de las Ciencias Experimentales (Matemáticas y Física)',
  'Pedagogía de las Ciencias Experimentales (Química y Biología)',
  'Pedagogía de los Idiomas Nacionales y Extranjeros',
  'Psicología',
  'Psicología Educativa',
  'Software',
  'Telecomunicaciones',
  'Textiles',
  'Fisioterapia',
];
