// <auto-generated />
using System;
using Kubix.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kubix.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContextoApp))]
    partial class ContextoAppModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kubix.Domain.Entities.AlertaSos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DisparadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fired_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<DateTimeOffset?>("ResueltaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResueltaPor")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ViajeId");

                    b.HasIndex("UniversidadId", "Estado");

                    b.ToTable("sos_alerts", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Calificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("CalificadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("rated_id");

                    b.Property<Guid>("CalificadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("rater_id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Estrellas")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("CalificadoId");

                    b.HasIndex("CalificadorId");

                    b.HasIndex("UniversidadId");

                    b.HasIndex("ViajeId", "CalificadorId", "CalificadoId")
                        .IsUnique();

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Campus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId", "Nombre")
                        .IsUnique();

                    b.ToTable("campuses", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.ConfiguracionUniversidad", b =>
                {
                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("CalificacionMinimaConductor")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("min_driver_rating");

                    b.Property<string>("CorreoSoporte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("support_email");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DominioCorreoPermitido")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("allowed_email_domain");

                    b.Property<decimal>("FactorCo2KgKm")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("co2_factor_kg_km");

                    b.Property<bool>("GamificacionHabilitada")
                        .HasColumnType("boolean")
                        .HasColumnName("gamification_enabled");

                    b.Property<int>("MaxViajesDiariosPorConductor")
                        .HasColumnType("integer")
                        .HasColumnName("max_daily_trips_per_driver");

                    b.Property<bool>("NotificarBloqueo")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_block");

                    b.Property<bool>("NotificarReporteSemanal")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_weekly_report");

                    b.Property<bool>("NotificarSos")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_sos");

                    b.Property<bool>("SeguimientoCo2Habilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("co2_tracking_enabled");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.HasKey("UniversidadId");

                    b.ToTable("university_settings", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.ContactoEmergencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Relacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("relationship");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("emergency_contacts", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.EventoAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UniversidadId", "Tipo", "CreadoEn");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("read");

                    b.Property<string>("RolDestinatario")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recipient_role");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid?>("UsuarioDestinatarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioDestinatarioId");

                    b.HasIndex("UniversidadId", "Leida", "CreadoEn");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.PingUbicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ViajeId", "UsuarioId", "RegistradoEn");

                    b.ToTable("location_pings", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.SolicitudRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<string>("Carrera")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("career");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecididoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecididoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NumeroIdentificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_number");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<string>("VehiculoJson")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_json");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("UniversidadId");

                    b.ToTable("registration_requests", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.SolicitudViaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("PasajeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<double>("RecogidaLat")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_lat");

                    b.Property<double>("RecogidaLng")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_lng");

                    b.Property<string>("RecogidaTexto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pickup_text");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid>("ViajeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("PasajeroId");

                    b.HasIndex("UniversidadId");

                    b.HasIndex("ViajeId", "PasajeroId")
                        .IsUnique();

                    b.ToTable("ride_requests", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.TokenRefresco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HashToken")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.TransaccionEcoToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdFuente")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_id");

                    b.Property<int>("Monto")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.HasIndex("UsuarioId", "Tipo", "IdFuente")
                        .IsUnique();

                    b.ToTable("eco_token_transactions", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Universidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("universities", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("BalanceEco")
                        .HasColumnType("integer")
                        .HasColumnName("eco_balance");

                    b.Property<Guid?>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<string>("Carrera")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("career");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<int>("EcoVitalicio")
                        .HasColumnType("integer")
                        .HasColumnName("eco_lifetime");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NumeroIdentificacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_number");

                    b.Property<decimal>("PromedioCalificacion")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating_avg");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid?>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("UniversidadId");

                    b.HasIndex("Correo", "UniversidadId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("AsientosTotales")
                        .HasColumnType("integer")
                        .HasColumnName("seats_total");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MarcaModelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("make_model");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Viaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("AsientosDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("seats_available");

                    b.Property<Guid>("CampusDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_campus_id");

                    b.Property<decimal>("Co2AhorradoKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("co2_saved_kg");

                    b.Property<DateTimeOffset?>("CompletadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConductorId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DistanciaKm")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("distance_km");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("IniciadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<double>("OrigenLat")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_lat");

                    b.Property<double>("OrigenLng")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_lng");

                    b.Property<string>("OrigenTexto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origin_text");

                    b.Property<string>("Polilinea")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("polyline");

                    b.Property<DateTimeOffset>("SaleEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at");

                    b.Property<Guid>("UniversidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.HasKey("Id");

                    b.HasIndex("CampusDestinoId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("UniversidadId", "Estado", "SaleEn");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Kubix.Domain.Entities.AlertaSos", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Viaje", "Viaje")
                        .WithMany()
                        .HasForeignKey("ViajeId");

                    b.Navigation("Universidad");

                    b.Navigation("Usuario");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Calificacion", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Usuario", "Calificado")
                        .WithMany()
                        .HasForeignKey("CalificadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Usuario", "Calificador")
                        .WithMany()
                        .HasForeignKey("CalificadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Viaje", "Viaje")
                        .WithMany("Calificaciones")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calificado");

                    b.Navigation("Calificador");

                    b.Navigation("Universidad");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Campus", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany("Sedes")
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.ConfiguracionUniversidad", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithOne("Configuracion")
                        .HasForeignKey("Kubix.Domain.Entities.ConfiguracionUniversidad", "UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.ContactoEmergencia", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ContactosEmergencia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.EventoAuditoria", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId");

                    b.HasOne("Kubix.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Universidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Usuario", "UsuarioDestinatario")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinatarioId");

                    b.Navigation("Universidad");

                    b.Navigation("UsuarioDestinatario");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.PingUbicacion", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Viaje", "Viaje")
                        .WithMany("PingsUbicacion")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");

                    b.Navigation("Usuario");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.SolicitudRegistro", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.SolicitudViaje", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Usuario", "Pasajero")
                        .WithMany()
                        .HasForeignKey("PasajeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Viaje", "Viaje")
                        .WithMany("SolicitudesViaje")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasajero");

                    b.Navigation("Universidad");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.TokenRefresco", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TokensRefresco")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.TransaccionEcoToken", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId");

                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany("Usuarios")
                        .HasForeignKey("UniversidadId");

                    b.Navigation("Campus");

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Viaje", b =>
                {
                    b.HasOne("Kubix.Domain.Entities.Campus", "CampusDestino")
                        .WithMany()
                        .HasForeignKey("CampusDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Usuario", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kubix.Domain.Entities.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampusDestino");

                    b.Navigation("Conductor");

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Universidad", b =>
                {
                    b.Navigation("Configuracion");

                    b.Navigation("Sedes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ContactosEmergencia");

                    b.Navigation("TokensRefresco");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Kubix.Domain.Entities.Viaje", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("PingsUbicacion");

                    b.Navigation("SolicitudesViaje");
                });
#pragma warning restore 612, 618
        }
    }
}
